apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ipmac-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: datpham23/frontend:latest
          imagePullPolicy: Always
          env:
            - name: VITE_BASE_URL
              value: "http://frontend:80"
            - name: VITE_API_URL
              value: "http://common-service:8080/api"
            - name: VITE_KEYCLOAK_URL
              value: "http://app.ipmac.dat/auth"
            - name: VITE_KEYCLOAK_REALM
              value: "ipmac"
            - name: VITE_KEYCLOAK_CLIENT_ID
              value: "frontend"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ipmac-app
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipmac-app-ingress
  namespace: ipmac-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Add other annotations based on your ingress controller
spec:
  ingressClassName: nginx  # Updated from the deprecated annotation
  rules:
    - host: app.ipmac.dat  # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: common-service
                port:
                  number: 8080
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - path: /kafka-ui
            pathType: Prefix
            backend:
              service:
                name: kafka-ui
                port:
                  number: 8080