apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-service
  namespace: ipmac-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: common-service
  template:
    metadata:
      labels:
        app: common-service
    spec:
      containers:
      - name: common-service
        image: datpham23/common-service:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: KEYCLOAK_AUTH_SERVER_URL
          value: "http://keycloak:8080/auth"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: common-service
  namespace: ipmac-app
spec:
  selector:
    app: common-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP