apiVersion: v1
kind: Namespace
metadata:
  name: ipmac-app

---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus

---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak

---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka

