apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "keycloak.fullname" . }}-db-pvc
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storageSize }}