apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}-db
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "keycloak.name" . }}-db
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "keycloak.name" . }}-db
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: postgresql
        image: "{{ .Values.database.image }}:{{ .Values.database.tag }}"
        imagePullPolicy: {{ .Values.database.pullPolicy }}
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_USER
          value: {{ .Values.database.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.password | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.database.name | quote }}
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: {{ include "keycloak.fullname" . }}-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-db
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  selector:
    app.kubernetes.io/name: {{ include "keycloak.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: 5432
    name: postgresql
    targetPort: 5432